# CMake generated Testfile for 
# Source directory: /home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests
# Build directory: /home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SelSortBasic.OneElementFindMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortBasic.OneElementFindMin" "--gtest_color=yes")
add_test(SelSortBasic.ThreeElementFindMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortBasic.ThreeElementFindMin" "--gtest_color=yes")
add_test(SelSortBasic.TenElementFindMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortBasic.TenElementFindMin" "--gtest_color=yes")
add_test(SelSortBasic.ThreeElementSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortBasic.ThreeElementSort" "--gtest_color=yes")
add_test(SelSortBasic.TenElementSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortBasic.TenElementSort" "--gtest_color=yes")
add_test(SelSortJTest.SameElementManyTimesMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.SameElementManyTimesMin" "--gtest_color=yes")
add_test(SelSortJTest.FirstElementMinSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.FirstElementMinSort" "--gtest_color=yes")
add_test(SelSortJTest.LastElementMinSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.LastElementMinSort" "--gtest_color=yes")
add_test(SelSortJTest.ThreeEqualValuesSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.ThreeEqualValuesSort" "--gtest_color=yes")
add_test(SelSortJTest.ThreeEqualNegativeValuesSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.ThreeEqualNegativeValuesSort" "--gtest_color=yes")
add_test(SelSortJTest.ReversedListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.ReversedListSort" "--gtest_color=yes")
add_test(SelSortJTest.PointerIntegrity "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.PointerIntegrity" "--gtest_color=yes")
add_test(SelSortJTest.EmptyListMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTest.EmptyListMin" "--gtest_color=yes")
add_test(SelSortJTestStress.TenThousandElementMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.TenThousandElementMin" "--gtest_color=yes")
add_test(SelSortJTestStress.HundredThousandElementMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.HundredThousandElementMin" "--gtest_color=yes")
add_test(SelSortJTestStress.MillionElementMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.MillionElementMin" "--gtest_color=yes")
add_test(SelSortJTestStress.HundredListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.HundredListSort" "--gtest_color=yes")
add_test(SelSortJTestStress.ThousandListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.ThousandListSort" "--gtest_color=yes")
add_test(SelSortJTestStress.TenThousandListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.TenThousandListSort" "--gtest_color=yes")
add_test(SelSortJTestStress.FiftyThousandListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestStress.FiftyThousandListSort" "--gtest_color=yes")
add_test(SelSortJTestRuntime.ThousandListMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.ThousandListMin" "--gtest_color=yes")
add_test(SelSortJTestRuntime.TenThousandListMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.TenThousandListMin" "--gtest_color=yes")
add_test(SelSortJTestRuntime.HundredThousandListMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.HundredThousandListMin" "--gtest_color=yes")
add_test(SelSortJTestRuntime.MillionListMin "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.MillionListMin" "--gtest_color=yes")
add_test(SelSortJTestRuntime.ThousandListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.ThousandListSort" "--gtest_color=yes")
add_test(SelSortJTestRuntime.TenThousandListSort "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/homework-submission/hw-wisnia/hw2/hw2-check/selection_sort_tests/selection_sort_test" "--gtest_filter=SelSortJTestRuntime.TenThousandListSort" "--gtest_color=yes")
