all: parser
	
parser: Bag.cpp Board.cpp ConsolePrinter.cpp Dictionary.cpp ExchangeMove.cpp Move.cpp PassMove.cpp PlaceMove.cpp Player.cpp Game.cpp
	g++ -g -Wall -std=c++11 Bag.cpp Board.cpp ConsolePrinter.cpp Dictionary.cpp ExchangeMove.cpp Move.cpp PassMove.cpp PlaceMove.cpp Player.cpp Game.cpp -o scrabble